/*
VISUALIZAR LOS NOMBRES DE LOS CLIENTES Y LA CANTIDAD
DE ENCARGOS REALIZADOS INCLUYENDO LOS QUE NO HAYAN REALIZADO
ENCARGOS 
*/
SELECT c.nombre, COUNT(e.id) AS 'N° ENCARGOS' FROM clientes c
LEFT JOIN encargos e ON c.id = e.cliente_id
GROUP BY 1;